### ISSUE TITLE
The highlight of % symbol.

### ISSUE THREAD

**Issue by npes87184** [edentsai/tig-theme-molokai#1]
Hi,

Is it possible to disable the highlight of % symbol in the right down corner?

Thanks.

**Comment by edentsai** [comment]
Sorry, I can't found a way to disable the highlight of  the % symbol in the right down corner.

Reference: http://jonas.nitro.dk/tig/tigrc.5.html

**Comment by edentsai** [comment]
I tried default .tigrc that the % symbol seems to be highlighted always

BUT...when my focus leaving iTerm2,  the % symbol will be unhighlighted.
I guess it was effected by the iTerm2/Terminal's cursor?

<img width="718" alt="tig-screen-when-focus-on" src="https://cloud.githubusercontent.com/assets/5071526/24716707/780bcf9c-1a62-11e7-928a-edb8a888893b.png">
<img width="511" alt="tig-screen-when-focus-lost" src="https://cloud.githubusercontent.com/assets/5071526/24716713/7afa8ec8-1a62-11e7-95c2-a8c0476c2431.png">

**Comment by npes87184** [comment]
Looks like it has been fixed in the latest tig.
