### ISSUE TITLE
🎸  Thank You! This is Awesome 🚀   && License request/advice/whatever

### ISSUE THREAD

**Issue by diffalot** [edentsai/tig-theme-molokai#3]
This works really well, and I've been enjoying it for a couple of weeks now.  Thank you very much for putting this together.

I've been rolling the idea of making a base 16 template for tig around in my head, and I was wondering if you'd mind if I comparatively analyzed the color choices you made while working with the limited palette available to you. I am asking if I can do the same with a Gruvbox theme I found last week, so I'll have multiple almost matches to pull data from.

The plan is to generate some some tables aroung how the known [monokai](https://github.com/base16-builder/base16-builder/blob/master/db/schemes/monokai.yml) and [gruvbox](https://github.com/base16-builder/base16-builder/blob/master/db/schemes/monokai.yml) palettes are mapped to specific areas of tig then use that as a base to begin looking at other palettes and a model to apply them.

This may all be beyond my ability as an engineer, but I want to give it a try.

Is that cool with you?

**Comment by edentsai** [comment]
It's ok, never mind.
